image: archlinux
packages:
  - libsass
  - sassc
  - nodejs
  - npm
sources:
  - https://git.sr.ht/~tcarrio/tom.carrio.dev
  - https://git.sr.ht/~tcarrio/build-helpers
environment:
  deploy_dir: .
  project_dir: tom.carrio.dev
secrets:
  - f34d2d66-6293-4072-bead-7478eb611c60
tasks:
  - install_netlify: |
      sudo npm i -g netlify-cli
      netlify --telemetry-disable
  - sass_build: |
      cd $project_dir
      mkdir -p assets/css
      sassc assets/scss/index.scss > assets/css/index.css
  - deploy_netlify: |
      source ./build-helpers/all.sh
      cd $project_dir
      if compare_branch master
      then
        netlify deploy -d $deploy_dir
      else
        netlify deploy -d $deploy_dir --prod
      fi